### PR TITLE
Never send us-east-1 as a requested region for CreateBucket

### LINKED ISSUE #9: AWS::S3->add_bucket location param is undocumented and buggy
This parameter is not documented. While it _shouldn't_ be required, it's passed to the request whether it was specified or not. So if I don't specify it then it ends up being passed as an `undef` and failing the TC for the `AWS::S3::Request::CreateBucket` `location` attribute.

### PR DESCRIPTION
**Pull request by autarch**
If no bucket location is specified or if us-east-1 is asked for we must not
include an XML body at all. Explicitly asking for us-east-1 causes S3 to
return an error.

Fixes #9.

### CODE REVIEW

File: lib/AWS/S3/Request/CreateBucket.pm [hunk 1]
```diff
@@ -16,23 +16,25 @@ has 'location' => (
...
+    if ( $s->location && $s->location ne 'us-east-1' ) {
+        $xml = <<"XML";
 <CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> 
-  <LocationConstraint>@{[ $s->location || 'us-east-1' ]}</LocationConstraint> 
+  <LocationConstraint>@{[ $s->location ]}</LocationConstraint>
 </CreateBucketConfiguration>
 XML
+    }
+
+    print $xml;
```
Comment (leejo) [inline lib/AWS/S3/Request/CreateBucket.pm:37]: debug?

**Comment by leejo** [comment]
Merged, removed the debug, v0.15 on its way to CPAN. Ta!
